In [2]:
#from Lists

import pandas as pd

data=[["Pragati",21],["Rani",22],["gauri",21]]
df=pd.DataFrame(data,columns=["Name","age"])
df

      Name  age
0  Pragati   21
1     Rani   22
2    gauri   21

In [4]:
#From dict of lists

a={
    "Name":['Alice',"Joe","Rehant"],
    "age":[21,22,23]
}
df=pd.DataFrame(a)
df

     Name  age
0   Alice   21
1     Joe   22
2  Rehant   23

In [5]:
#from numpy arrays
import numpy as np

arr=np.array([[1,2],[3,4]])
df=pd.DataFrame(arr,columns=["A","B"])
df

   A  B
0  1  2
1  3  4

In [6]:
#From SCV
df=pd.read_csv("data.csv")
df

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [7]:
#from excel
df=pd.read_excel("data.xlsx")
df

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [8]:
pd.read_csv("data.csv", usecols=["Name", "Age"])

         Name  Age
0      Aniket   21
1         Ram   22
2        Siya   21
3         Raj   16
4      Prachi   22
5      Soumya   14
6      Yashmi   17
7     Nikitha   18
8   Shrinidhi   15
9      Tanaya   14
10     Taniya   12

In [10]:
#From web
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
#EDA
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [14]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [15]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [16]:
df.shape

(244, 7)