In [1]:
import pandas as pd

df=pd.read_csv("sample_students.csv")
df

     ID        Name  Age       City  Score Passed
0     1    Student1   20     Mumbai     37     No
1     2    Student2   21      Delhi     44     No
2     3    Student3   22  Bangalore     51    Yes
3     4    Student4   23  Hyderabad     58    Yes
4     5    Student5   19    Chennai     65    Yes
..  ...         ...  ...        ...    ...    ...
95   96   Student96   20       Pune     72    Yes
96   97   Student97   21     Mumbai     79    Yes
97   98   Student98   22      Delhi     86    Yes
98   99   Student99   23  Bangalore     93    Yes
99  100  Student100   19  Hyderabad     30     No

[100 rows x 6 columns]

In [3]:
df["Name"]

0       Student1
1       Student2
2       Student3
3       Student4
4       Student5
         ...
95     Student96
96     Student97
97     Student98
98     Student99
99    Student100
Name: Name, Length: 100, dtype: object

In [5]:
df[["Name","Score"]]

          Name  Score
0     Student1     37
1     Student2     44
2     Student3     51
3     Student4     58
4     Student5     65
..         ...    ...
95   Student96     72
96   Student97     79
97   Student98     86
98   Student99     93
99  Student100     30

[100 rows x 2 columns]

In [6]:
df.loc[0]

ID               1
Name      Student1
Age             20
City        Mumbai
Score           37
Passed          No
Name: 0, dtype: object

In [7]:
df.iloc[0]

ID               1
Name      Student1
Age             20
City        Mumbai
Score           37
Passed          No
Name: 0, dtype: object

In [9]:
df.loc[0,"Name"]

'Student1'

In [10]:
df.iloc[0,1]

'Student1'

In [12]:
df.loc[0:2,["Name","Age"]]

       Name  Age
0  Student1   20
1  Student2   21
2  Student3   22

In [13]:
df.iloc[0:2,0:2]

   ID      Name
0   1  Student1
1   2  Student2

In [14]:
df.at[0,"Name"]

'Student1'

In [15]:
df.iat[0,1]

'Student1'

In [18]:
#Filtering
df[df['Age']>21]

    ID       Name  Age       City  Score Passed
2    3   Student3   22  Bangalore     51    Yes
3    4   Student4   23  Hyderabad     58    Yes
7    8   Student8   22      Delhi     86    Yes
8    9   Student9   23  Bangalore     93    Yes
12  13  Student13   22     Mumbai     51    Yes
13  14  Student14   23      Delhi     58    Yes
17  18  Student18   22       Pune     86    Yes
18  19  Student19   23     Mumbai     93    Yes
22  23  Student23   22    Chennai     51    Yes
23  24  Student24   23       Pune     58    Yes
27  28  Student28   22  Hyderabad     86    Yes
28  29  Student29   23    Chennai     93    Yes
32  33  Student33   22  Bangalore     51    Yes
33  34  Student34   23  Hyderabad     58    Yes
37  38  Student38   22      Delhi     86    Yes
38  39  Student39   23  Bangalore     93    Yes
42  43  Student43   22     Mumbai     51    Yes
43  44  Student44   23      Delhi     58    Yes
47  48  Student48   22       Pune     86    Yes
48  49  Student49   23     Mumbai     93    Yes
52  53  Student53   22    Chennai     51    Yes
53  54  Student54   23       Pune     58    Yes
57  58  Student58   22  Hyderabad     86    Yes
58  59  Student59   23    Chennai     93    Yes
62  63  Student63   22  Bangalore     51    Yes
63  64  Student64   23  Hyderabad     58    Yes
67  68  Student68   22      Delhi     86    Yes
68  69  Student69   23  Bangalore     93    Yes
72  73  Student73   22     Mumbai     51    Yes
73  74  Student74   23      Delhi     58    Yes
77  78  Student78   22       Pune     86    Yes
78  79  Student79   23     Mumbai     93    Yes
82  83  Student83   22    Chennai     51    Yes
83  84  Student84   23       Pune     58    Yes
87  88  Student88   22  Hyderabad     86    Yes
88  89  Student89   23    Chennai     93    Yes
92  93  Student93   22  Bangalore     51    Yes
93  94  Student94   23  Hyderabad     58    Yes
97  98  Student98   22      Delhi     86    Yes
98  99  Student99   23  Bangalore     93    Yes

In [20]:

df[(df["Name"] == "Bob") | (df["Age"] < 30)]

     ID        Name  Age       City  Score Passed
0     1    Student1   20     Mumbai     37     No
1     2    Student2   21      Delhi     44     No
2     3    Student3   22  Bangalore     51    Yes
3     4    Student4   23  Hyderabad     58    Yes
4     5    Student5   19    Chennai     65    Yes
..  ...         ...  ...        ...    ...    ...
95   96   Student96   20       Pune     72    Yes
96   97   Student97   21     Mumbai     79    Yes
97   98   Student98   22      Delhi     86    Yes
98   99   Student99   23  Bangalore     93    Yes
99  100  Student100   19  Hyderabad     30     No

[100 rows x 6 columns]

In [21]:
df[(df["Age"] > 20) & (df["City"] == "Delhi")]

    ID       Name  Age   City  Score Passed
1    2   Student2   21  Delhi     44     No
7    8   Student8   22  Delhi     86    Yes
13  14  Student14   23  Delhi     58    Yes
31  32  Student32   21  Delhi     44     No
37  38  Student38   22  Delhi     86    Yes
43  44  Student44   23  Delhi     58    Yes
61  62  Student62   21  Delhi     44     No
67  68  Student68   22  Delhi     86    Yes
73  74  Student74   23  Delhi     58    Yes
91  92  Student92   21  Delhi     44     No
97  98  Student98   22  Delhi     86    Yes