In [1]:
import pandas as pd

df=pd.read_csv("data_cleaning_sample.csv")

In [2]:
df

    ID       Name   Age     City  Score
0    1   Student1  21.0     Pune   53.0
1    2   Student2  22.0   Mumbai   56.0
2    3   Student3  23.0      NaN   59.0
3    4        NaN  24.0    Delhi   62.0
4    5   Student5  20.0  Chennai    NaN
5    6   Student6   NaN     Pune   68.0
6    7   Student7  22.0   Mumbai   71.0
7    8        NaN  23.0      NaN   74.0
8    9   Student9  24.0    Delhi   77.0
9   10  Student10  20.0  Chennai    NaN
10  11  Student11  21.0     Pune   83.0
11  12        NaN   NaN   Mumbai   86.0
12  13  Student13  23.0      NaN   89.0
13  14  Student14  24.0    Delhi   52.0
14  15  Student15  20.0  Chennai    NaN
15  16        NaN  21.0     Pune   58.0
16  17  Student17  22.0   Mumbai   61.0
17  18  Student18   NaN      NaN   64.0
18  19  Student19  24.0    Delhi   67.0
19  20        NaN  20.0  Chennai    NaN

In [4]:
#Check missing values

df.isnull()

       ID   Name    Age   City  Score
0   False  False  False  False  False
1   False  False  False  False  False
2   False  False  False   True  False
3   False   True  False  False  False
4   False  False  False  False   True
5   False  False   True  False  False
6   False  False  False  False  False
7   False   True  False   True  False
8   False  False  False  False  False
9   False  False  False  False   True
10  False  False  False  False  False
11  False   True   True  False  False
12  False  False  False   True  False
13  False  False  False  False  False
14  False  False  False  False   True
15  False   True  False  False  False
16  False  False  False  False  False
17  False  False   True   True  False
18  False  False  False  False  False
19  False   True  False  False   True

In [5]:
df.isnull().sum()

ID       0
Name     5
Age      3
City     4
Score    4
dtype: int64

In [ ]:
#Drop missing data

In [6]:
df.dropna()    # Drop rows with *any* missing values

    ID       Name   Age    City  Score
0    1   Student1  21.0    Pune   53.0
1    2   Student2  22.0  Mumbai   56.0
6    7   Student7  22.0  Mumbai   71.0
8    9   Student9  24.0   Delhi   77.0
10  11  Student11  21.0    Pune   83.0
13  14  Student14  24.0   Delhi   52.0
16  17  Student17  22.0  Mumbai   61.0
18  19  Student19  24.0   Delhi   67.0

In [7]:
df.dropna(axis=1)  # Drop columns with missing values

    ID
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
19  20

In [9]:
#Fill Missing Data
df.fillna(1)

    ID       Name   Age     City  Score
0    1   Student1  21.0     Pune   53.0
1    2   Student2  22.0   Mumbai   56.0
2    3   Student3  23.0        1   59.0
3    4          1  24.0    Delhi   62.0
4    5   Student5  20.0  Chennai    1.0
5    6   Student6   1.0     Pune   68.0
6    7   Student7  22.0   Mumbai   71.0
7    8          1  23.0        1   74.0
8    9   Student9  24.0    Delhi   77.0
9   10  Student10  20.0  Chennai    1.0
10  11  Student11  21.0     Pune   83.0
11  12          1   1.0   Mumbai   86.0
12  13  Student13  23.0        1   89.0
13  14  Student14  24.0    Delhi   52.0
14  15  Student15  20.0  Chennai    1.0
15  16          1  21.0     Pune   58.0
16  17  Student17  22.0   Mumbai   61.0
17  18  Student18   1.0        1   64.0
18  19  Student19  24.0    Delhi   67.0
19  20          1  20.0  Chennai    1.0

In [10]:
df["Age"].fillna(df["Age"].mean())

0     21.0
1     22.0
2     23.0
3     24.0
4     20.0
5     22.0
6     22.0
7     23.0
8     24.0
9     20.0
10    21.0
11    22.0
12    23.0
13    24.0
14    20.0
15    21.0
16    22.0
17    22.0
18    24.0
19    20.0
Name: Age, dtype: float64

In [11]:
df.ffill()

    ID       Name   Age     City  Score
0    1   Student1  21.0     Pune   53.0
1    2   Student2  22.0   Mumbai   56.0
2    3   Student3  23.0   Mumbai   59.0
3    4   Student3  24.0    Delhi   62.0
4    5   Student5  20.0  Chennai   62.0
5    6   Student6  20.0     Pune   68.0
6    7   Student7  22.0   Mumbai   71.0
7    8   Student7  23.0   Mumbai   74.0
8    9   Student9  24.0    Delhi   77.0
9   10  Student10  20.0  Chennai   77.0
10  11  Student11  21.0     Pune   83.0
11  12  Student11  21.0   Mumbai   86.0
12  13  Student13  23.0   Mumbai   89.0
13  14  Student14  24.0    Delhi   52.0
14  15  Student15  20.0  Chennai   52.0
15  16  Student15  21.0     Pune   58.0
16  17  Student17  22.0   Mumbai   61.0
17  18  Student18  22.0   Mumbai   64.0
18  19  Student19  24.0    Delhi   67.0
19  20  Student19  20.0  Chennai   67.0

In [12]:
df.bfill()

    ID       Name   Age     City  Score
0    1   Student1  21.0     Pune   53.0
1    2   Student2  22.0   Mumbai   56.0
2    3   Student3  23.0    Delhi   59.0
3    4   Student5  24.0    Delhi   62.0
4    5   Student5  20.0  Chennai   68.0
5    6   Student6  22.0     Pune   68.0
6    7   Student7  22.0   Mumbai   71.0
7    8   Student9  23.0    Delhi   74.0
8    9   Student9  24.0    Delhi   77.0
9   10  Student10  20.0  Chennai   83.0
10  11  Student11  21.0     Pune   83.0
11  12  Student13  23.0   Mumbai   86.0
12  13  Student13  23.0    Delhi   89.0
13  14  Student14  24.0    Delhi   52.0
14  15  Student15  20.0  Chennai   58.0
15  16  Student17  21.0     Pune   58.0
16  17  Student17  22.0   Mumbai   61.0
17  18  Student18  24.0    Delhi   64.0
18  19  Student19  24.0    Delhi   67.0
19  20        NaN  20.0  Chennai    NaN

In [13]:
#Detecting & Removing Duplicates

df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [14]:
df.drop_duplicates()

    ID       Name   Age     City  Score
0    1   Student1  21.0     Pune   53.0
1    2   Student2  22.0   Mumbai   56.0
2    3   Student3  23.0      NaN   59.0
3    4        NaN  24.0    Delhi   62.0
4    5   Student5  20.0  Chennai    NaN
5    6   Student6   NaN     Pune   68.0
6    7   Student7  22.0   Mumbai   71.0
7    8        NaN  23.0      NaN   74.0
8    9   Student9  24.0    Delhi   77.0
9   10  Student10  20.0  Chennai    NaN
10  11  Student11  21.0     Pune   83.0
11  12        NaN   NaN   Mumbai   86.0
12  13  Student13  23.0      NaN   89.0
13  14  Student14  24.0    Delhi   52.0
14  15  Student15  20.0  Chennai    NaN
15  16        NaN  21.0     Pune   58.0
16  17  Student17  22.0   Mumbai   61.0
17  18  Student18   NaN      NaN   64.0
18  19  Student19  24.0    Delhi   67.0
19  20        NaN  20.0  Chennai    NaN

In [15]:
df.duplicated(subset=["Name", "Age"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [16]:
#String Operations with .str
df["Name"].str.lower()

0      student1
1      student2
2      student3
3           NaN
4      student5
5      student6
6      student7
7           NaN
8      student9
9     student10
10    student11
11          NaN
12    student13
13    student14
14    student15
15          NaN
16    student17
17    student18
18    student19
19          NaN
Name: Name, dtype: object

In [17]:
df["City"].str.contains("Delhi",case=False)

0     False
1     False
2       NaN
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10    False
11    False
12      NaN
13     True
14    False
15    False
16    False
17      NaN
18     True
19    False
Name: City, dtype: object

In [19]:
df["City"].str.split("@")

0        [Pune]
1      [Mumbai]
2           NaN
3       [Delhi]
4     [Chennai]
5        [Pune]
6      [Mumbai]
7           NaN
8       [Delhi]
9     [Chennai]
10       [Pune]
11     [Mumbai]
12          NaN
13      [Delhi]
14    [Chennai]
15       [Pune]
16     [Mumbai]
17          NaN
18      [Delhi]
19    [Chennai]
Name: City, dtype: object

In [21]:
df["Name"].str.strip().str.upper()

0      STUDENT1
1      STUDENT2
2      STUDENT3
3           NaN
4      STUDENT5
5      STUDENT6
6      STUDENT7
7           NaN
8      STUDENT9
9     STUDENT10
10    STUDENT11
11          NaN
12    STUDENT13
13    STUDENT14
14    STUDENT15
15          NaN
16    STUDENT17
17    STUDENT18
18    STUDENT19
19          NaN
Name: Name, dtype: object

In [26]:
#Type Conversions with .astype()

In [27]:
df = df.dropna(subset=['Age'])
df['Age'] = df['Age'].astype(int)

In [28]:
df

    ID       Name  Age     City  Score
0    1   Student1   21     Pune   53.0
1    2   Student2   22   Mumbai   56.0
2    3   Student3   23      NaN   59.0
3    4        NaN   24    Delhi   62.0
4    5   Student5   20  Chennai    NaN
5    6   Student6   11     Pune   68.0
6    7   Student7   22   Mumbai   71.0
7    8        NaN   23      NaN   74.0
8    9   Student9   24    Delhi   77.0
9   10  Student10   20  Chennai    NaN
10  11  Student11   21     Pune   83.0
11  12        NaN   11   Mumbai   86.0
12  13  Student13   23      NaN   89.0
13  14  Student14   24    Delhi   52.0
14  15  Student15   20  Chennai    NaN
15  16        NaN   21     Pune   58.0
16  17  Student17   22   Mumbai   61.0
17  18  Student18   11      NaN   64.0
18  19  Student19   24    Delhi   67.0
19  20        NaN   20  Chennai    NaN

In [29]:
d=pd.read_csv("data_cleaning_with_dates.csv")

In [30]:
d

    ID       Name   Age     City  Score        Date
0    1   Student1  21.0     Pune   53.0         NaN
1    2   Student2  22.0   Mumbai   56.0  2024-01-02
2    3   Student3  23.0      NaN   59.0  2024-01-03
3    4        NaN  24.0    Delhi   62.0         NaN
4    5   Student5  20.0  Chennai    NaN  2024-01-05
5    6   Student6   NaN     Pune   68.0  2024-01-06
6    7   Student7  22.0   Mumbai   71.0         NaN
7    8        NaN  23.0      NaN   74.0  2024-01-08
8    9   Student9  24.0    Delhi   77.0  2024-01-09
9   10  Student10  20.0  Chennai    NaN         NaN
10  11  Student11  21.0     Pune   83.0  2024-01-11
11  12        NaN   NaN   Mumbai   86.0  2024-01-12
12  13  Student13  23.0      NaN   89.0         NaN
13  14  Student14  24.0    Delhi   52.0  2024-01-14
14  15  Student15  20.0  Chennai    NaN  2024-01-15
15  16        NaN  21.0     Pune   58.0         NaN
16  17  Student17  22.0   Mumbai   61.0  2024-01-17
17  18  Student18   NaN      NaN   64.0  2024-01-18
18  19  Student19  24.0    Delhi   67.0         NaN
19  20        NaN  20.0  Chennai    NaN  2024-01-20

In [31]:
d["Date"] = pd.to_datetime(d["Date"])

In [32]:
d

    ID       Name   Age     City  Score       Date
0    1   Student1  21.0     Pune   53.0        NaT
1    2   Student2  22.0   Mumbai   56.0 2024-01-02
2    3   Student3  23.0      NaN   59.0 2024-01-03
3    4        NaN  24.0    Delhi   62.0        NaT
4    5   Student5  20.0  Chennai    NaN 2024-01-05
5    6   Student6   NaN     Pune   68.0 2024-01-06
6    7   Student7  22.0   Mumbai   71.0        NaT
7    8        NaN  23.0      NaN   74.0 2024-01-08
8    9   Student9  24.0    Delhi   77.0 2024-01-09
9   10  Student10  20.0  Chennai    NaN        NaT
10  11  Student11  21.0     Pune   83.0 2024-01-11
11  12        NaN   NaN   Mumbai   86.0 2024-01-12
12  13  Student13  23.0      NaN   89.0        NaT
13  14  Student14  24.0    Delhi   52.0 2024-01-14
14  15  Student15  20.0  Chennai    NaN 2024-01-15
15  16        NaN  21.0     Pune   58.0        NaT
16  17  Student17  22.0   Mumbai   61.0 2024-01-17
17  18  Student18   NaN      NaN   64.0 2024-01-18
18  19  Student19  24.0    Delhi   67.0        NaT
19  20        NaN  20.0  Chennai    NaN 2024-01-20

In [33]:
d.dtypes

ID                int64
Name             object
Age             float64
City             object
Score           float64
Date     datetime64[ns]
dtype: object

In [35]:
#Applying Functions

d["Age"]=d["Age"].apply(lambda x:"Adult" if x>=18 else "Child")

In [36]:
d

    ID       Name    Age     City  Score       Date
0    1   Student1  Adult     Pune   53.0        NaT
1    2   Student2  Adult   Mumbai   56.0 2024-01-02
2    3   Student3  Adult      NaN   59.0 2024-01-03
3    4        NaN  Adult    Delhi   62.0        NaT
4    5   Student5  Adult  Chennai    NaN 2024-01-05
5    6   Student6  Child     Pune   68.0 2024-01-06
6    7   Student7  Adult   Mumbai   71.0        NaT
7    8        NaN  Adult      NaN   74.0 2024-01-08
8    9   Student9  Adult    Delhi   77.0 2024-01-09
9   10  Student10  Adult  Chennai    NaN        NaT
10  11  Student11  Adult     Pune   83.0 2024-01-11
11  12        NaN  Child   Mumbai   86.0 2024-01-12
12  13  Student13  Adult      NaN   89.0        NaT
13  14  Student14  Adult    Delhi   52.0 2024-01-14
14  15  Student15  Adult  Chennai    NaN 2024-01-15
15  16        NaN  Adult     Pune   58.0        NaT
16  17  Student17  Adult   Mumbai   61.0 2024-01-17
17  18  Student18  Child      NaN   64.0 2024-01-18
18  19  Student19  Adult    Delhi   67.0        NaT
19  20        NaN  Adult  Chennai    NaN 2024-01-20

In [37]:
city_map = {"D": "Delhi", "P": "Pune"}
d["City"] = d["City"].map(city_map)

In [38]:
d

    ID       Name    Age City  Score       Date
0    1   Student1  Adult  NaN   53.0        NaT
1    2   Student2  Adult  NaN   56.0 2024-01-02
2    3   Student3  Adult  NaN   59.0 2024-01-03
3    4        NaN  Adult  NaN   62.0        NaT
4    5   Student5  Adult  NaN    NaN 2024-01-05
5    6   Student6  Child  NaN   68.0 2024-01-06
6    7   Student7  Adult  NaN   71.0        NaT
7    8        NaN  Adult  NaN   74.0 2024-01-08
8    9   Student9  Adult  NaN   77.0 2024-01-09
9   10  Student10  Adult  NaN    NaN        NaT
10  11  Student11  Adult  NaN   83.0 2024-01-11
11  12        NaN  Child  NaN   86.0 2024-01-12
12  13  Student13  Adult  NaN   89.0        NaT
13  14  Student14  Adult  NaN   52.0 2024-01-14
14  15  Student15  Adult  NaN    NaN 2024-01-15
15  16        NaN  Adult  NaN   58.0        NaT
16  17  Student17  Adult  NaN   61.0 2024-01-17
17  18  Student18  Child  NaN   64.0 2024-01-18
18  19  Student19  Adult  NaN   67.0        NaT
19  20        NaN  Adult  NaN    NaN 2024-01-20

In [39]:
df["City"].replace({"Del": "Delhi", "Mum": "Mumbai"})

0        Pune
1      Mumbai
2         NaN
3       Delhi
4     Chennai
5        Pune
6      Mumbai
7         NaN
8       Delhi
9     Chennai
10       Pune
11     Mumbai
12        NaN
13      Delhi
14    Chennai
15       Pune
16     Mumbai
17        NaN
18      Delhi
19    Chennai
Name: City, dtype: object