In [ ]:
#Sorting & Ranking

In [1]:
import pandas as pd

df=pd.read_csv("data.csv")
df

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [2]:
df.sort_values("Age")

         Name    School  Age  Marks
10     Taniya       BPS   12     95
5      Soumya       BPS   14     90
9      Tanaya       CSM   14     85
8   Shrinidhi       BPS   15     87
3         Raj  Montfort   16     78
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
0      Aniket      CSPM   21     78
2        Siya      MEMS   21     56
1         Ram   Bhalero   22     67
4      Prachi       KVY   22     89

In [3]:
df.sort_values("Age",ascending=False)

         Name    School  Age  Marks
1         Ram   Bhalero   22     67
4      Prachi       KVY   22     89
0      Aniket      CSPM   21     78
2        Siya      MEMS   21     56
7     Nikitha       CSM   18     98
6      Yashmi       BPS   17     99
3         Raj  Montfort   16     78
8   Shrinidhi       BPS   15     87
5      Soumya       BPS   14     90
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [5]:
df.sort_values(["Age","Marks"])

         Name    School  Age  Marks
10     Taniya       BPS   12     95
9      Tanaya       CSM   14     85
5      Soumya       BPS   14     90
8   Shrinidhi       BPS   15     87
3         Raj  Montfort   16     78
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
2        Siya      MEMS   21     56
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
4      Prachi       KVY   22     89

In [7]:
#Reset Index
df.reset_index(drop=True,inplace=True)

In [8]:
df

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [9]:
df.sort_index()

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [10]:
df["Rank"]=df["Marks"].rank()

In [11]:
df

         Name    School  Age  Marks  Rank
0      Aniket      CSPM   21     78   3.5
1         Ram   Bhalero   22     67   2.0
2        Siya      MEMS   21     56   1.0
3         Raj  Montfort   16     78   3.5
4      Prachi       KVY   22     89   7.0
5      Soumya       BPS   14     90   8.0
6      Yashmi       BPS   17     99  11.0
7     Nikitha       CSM   18     98  10.0
8   Shrinidhi       BPS   15     87   6.0
9      Tanaya       CSM   14     85   5.0
10     Taniya       BPS   12     95   9.0

In [13]:
df["Rank"]=df["Marks"].rank(method="dense")

In [14]:
df

         Name    School  Age  Marks  Rank
0      Aniket      CSPM   21     78   3.0
1         Ram   Bhalero   22     67   2.0
2        Siya      MEMS   21     56   1.0
3         Raj  Montfort   16     78   3.0
4      Prachi       KVY   22     89   6.0
5      Soumya       BPS   14     90   7.0
6      Yashmi       BPS   17     99  10.0
7     Nikitha       CSM   18     98   9.0
8   Shrinidhi       BPS   15     87   5.0
9      Tanaya       CSM   14     85   4.0
10     Taniya       BPS   12     95   8.0

In [15]:
#Renaming col

df.rename(columns={"Marks": "Score"}, inplace=True)

In [16]:
df

         Name    School  Age  Score  Rank
0      Aniket      CSPM   21     78   3.0
1         Ram   Bhalero   22     67   2.0
2        Siya      MEMS   21     56   1.0
3         Raj  Montfort   16     78   3.0
4      Prachi       KVY   22     89   6.0
5      Soumya       BPS   14     90   7.0
6      Yashmi       BPS   17     99  10.0
7     Nikitha       CSM   18     98   9.0
8   Shrinidhi       BPS   15     87   5.0
9      Tanaya       CSM   14     85   4.0
10     Taniya       BPS   12     95   8.0

In [17]:
df.rename(index={0: "row1", 1: "row2"}, inplace=True)

In [18]:
df

           Name    School  Age  Score  Rank
row1     Aniket      CSPM   21     78   3.0
row2        Ram   Bhalero   22     67   2.0
2          Siya      MEMS   21     56   1.0
3           Raj  Montfort   16     78   3.0
4        Prachi       KVY   22     89   6.0
5        Soumya       BPS   14     90   7.0
6        Yashmi       BPS   17     99  10.0
7       Nikitha       CSM   18     98   9.0
8     Shrinidhi       BPS   15     87   5.0
9        Tanaya       CSM   14     85   4.0
10       Taniya       BPS   12     95   8.0

In [22]:
df = df[["Score", "Name", "Age"]] 
df

      Score       Name  Age
row1     78     Aniket   21
row2     67        Ram   22
2        56       Siya   21
3        78        Raj   16
4        89     Prachi   22
5        90     Soumya   14
6        99     Yashmi   17
7        98    Nikitha   18
8        87  Shrinidhi   15
9        85     Tanaya   14
10       95     Taniya   12

In [24]:
cols = ["Name"] + [col for col in df.columns if col != "Name"]
df = df[cols]
df

           Name  Score  Age
row1     Aniket     78   21
row2        Ram     67   22
2          Siya     56   21
3           Raj     78   16
4        Prachi     89   22
5        Soumya     90   14
6        Yashmi     99   17
7       Nikitha     98   18
8     Shrinidhi     87   15
9        Tanaya     85   14
10       Taniya     95   12