In [2]:
#Series

import pandas as pd

a=pd.Series([12,13,14,15])
print(a)

0    12
1    13
2    14
3    15
dtype: int64

In [3]:
b=pd.Series([20,56,67,90],index=['a','b','c','d'])
b

a    20
b    56
c    67
d    90
dtype: int64

In [8]:
# DataFrames

data={
    'name':["Prachi",'Pragati',"Soma"],
    'age':[21,20,19],
    'city':['Ballarpur','Chnadrapur','bamani']
}
df=pd.DataFrame(data)
df

      name  age        city
0   Prachi   21   Ballarpur
1  Pragati   20  Chnadrapur
2     Soma   19      bamani

In [10]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [3]:
import pandas as pd

dt={
    'name':["Prachi",'Pragati',"Sonali"],
    'age':[21,20,19],
    'city':['Ballarpur','Chnadrapur','bamani']
}
df=pd.DataFrame(dt)
df.index=['a','b','c']
df.columns=['Nam','sal','shahar']
df

       Nam  sal      shahar
a   Prachi   21   Ballarpur
b  Pragati   20  Chnadrapur
c   Sonali   19      bamani