In [1]:
import pandas as pd

df=pd.read_csv("sample_students.csv")

In [2]:
df

     ID        Name  Age       City  Score Passed
0     1    Student1   20     Mumbai     37     No
1     2    Student2   21      Delhi     44     No
2     3    Student3   22  Bangalore     51    Yes
3     4    Student4   23  Hyderabad     58    Yes
4     5    Student5   19    Chennai     65    Yes
..  ...         ...  ...        ...    ...    ...
95   96   Student96   20       Pune     72    Yes
96   97   Student97   21     Mumbai     79    Yes
97   98   Student98   22      Delhi     86    Yes
98   99   Student99   23  Bangalore     93    Yes
99  100  Student100   19  Hyderabad     30     No

[100 rows x 6 columns]

In [4]:
df.query("Age > 20 and City == 'Delhi'")

    ID       Name  Age   City  Score Passed
1    2   Student2   21  Delhi     44     No
7    8   Student8   22  Delhi     86    Yes
13  14  Student14   23  Delhi     58    Yes
31  32  Student32   21  Delhi     44     No
37  38  Student38   22  Delhi     86    Yes
43  44  Student44   23  Delhi     58    Yes
61  62  Student62   21  Delhi     44     No
67  68  Student68   22  Delhi     86    Yes
73  74  Student74   23  Delhi     58    Yes
91  92  Student92   21  Delhi     44     No
97  98  Student98   22  Delhi     86    Yes

In [7]:
col="Age"
df.query(f"{col}<22")

     ID        Name  Age       City  Score Passed
0     1    Student1   20     Mumbai     37     No
1     2    Student2   21      Delhi     44     No
4     5    Student5   19    Chennai     65    Yes
5     6    Student6   20       Pune     72    Yes
6     7    Student7   21     Mumbai     79    Yes
9    10   Student10   19  Hyderabad     30     No
10   11   Student11   20    Chennai     37     No
11   12   Student12   21       Pune     44     No
14   15   Student15   19  Bangalore     65    Yes
15   16   Student16   20  Hyderabad     72    Yes
16   17   Student17   21    Chennai     79    Yes
19   20   Student20   19      Delhi     30     No
20   21   Student21   20  Bangalore     37     No
21   22   Student22   21  Hyderabad     44     No
24   25   Student25   19     Mumbai     65    Yes
25   26   Student26   20      Delhi     72    Yes
26   27   Student27   21  Bangalore     79    Yes
29   30   Student30   19       Pune     30     No
30   31   Student31   20     Mumbai     37     No
31   32   Student32   21      Delhi     44     No
34   35   Student35   19    Chennai     65    Yes
35   36   Student36   20       Pune     72    Yes
36   37   Student37   21     Mumbai     79    Yes
39   40   Student40   19  Hyderabad     30     No
40   41   Student41   20    Chennai     37     No
41   42   Student42   21       Pune     44     No
44   45   Student45   19  Bangalore     65    Yes
45   46   Student46   20  Hyderabad     72    Yes
46   47   Student47   21    Chennai     79    Yes
49   50   Student50   19      Delhi     30     No
50   51   Student51   20  Bangalore     37     No
51   52   Student52   21  Hyderabad     44     No
54   55   Student55   19     Mumbai     65    Yes
55   56   Student56   20      Delhi     72    Yes
56   57   Student57   21  Bangalore     79    Yes
59   60   Student60   19       Pune     30     No
60   61   Student61   20     Mumbai     37     No
61   62   Student62   21      Delhi     44     No
64   65   Student65   19    Chennai     65    Yes
65   66   Student66   20       Pune     72    Yes
66   67   Student67   21     Mumbai     79    Yes
69   70   Student70   19  Hyderabad     30     No
70   71   Student71   20    Chennai     37     No
71   72   Student72   21       Pune     44     No
74   75   Student75   19  Bangalore     65    Yes
75   76   Student76   20  Hyderabad     72    Yes
76   77   Student77   21    Chennai     79    Yes
79   80   Student80   19      Delhi     30     No
80   81   Student81   20  Bangalore     37     No
81   82   Student82   21  Hyderabad     44     No
84   85   Student85   19     Mumbai     65    Yes
85   86   Student86   20      Delhi     72    Yes
86   87   Student87   21  Bangalore     79    Yes
89   90   Student90   19       Pune     30     No
90   91   Student91   20     Mumbai     37     No
91   92   Student92   21      Delhi     44     No
94   95   Student95   19    Chennai     65    Yes
95   96   Student96   20       Pune     72    Yes
96   97   Student97   21     Mumbai     79    Yes
99  100  Student100   19  Hyderabad     30     No

In [11]:
#rules and tips

#1. Column names become variables
df.query("Age > 22 and City == 'Delhi'")

    ID       Name  Age   City  Score Passed
13  14  Student14   23  Delhi     58    Yes
43  44  Student44   23  Delhi     58    Yes
73  74  Student74   23  Delhi     58    Yes

In [15]:
#2. String values must be in quotes

df.query("City == 'Delhi'")

    ID       Name  Age   City  Score Passed
1    2   Student2   21  Delhi     44     No
7    8   Student8   22  Delhi     86    Yes
13  14  Student14   23  Delhi     58    Yes
19  20  Student20   19  Delhi     30     No
25  26  Student26   20  Delhi     72    Yes
31  32  Student32   21  Delhi     44     No
37  38  Student38   22  Delhi     86    Yes
43  44  Student44   23  Delhi     58    Yes
49  50  Student50   19  Delhi     30     No
55  56  Student56   20  Delhi     72    Yes
61  62  Student62   21  Delhi     44     No
67  68  Student68   22  Delhi     86    Yes
73  74  Student74   23  Delhi     58    Yes
79  80  Student80   19  Delhi     30     No
85  86  Student86   20  Delhi     72    Yes
91  92  Student92   21  Delhi     44     No
97  98  Student98   22  Delhi     86    Yes

In [16]:
#3. Use backticks for column names with spaces or special characters

df.query("`Score` == 58")

    ID       Name  Age       City  Score Passed
3    4   Student4   23  Hyderabad     58    Yes
13  14  Student14   23      Delhi     58    Yes
23  24  Student24   23       Pune     58    Yes
33  34  Student34   23  Hyderabad     58    Yes
43  44  Student44   23      Delhi     58    Yes
53  54  Student54   23       Pune     58    Yes
63  64  Student64   23  Hyderabad     58    Yes
73  74  Student74   23      Delhi     58    Yes
83  84  Student84   23       Pune     58    Yes
93  94  Student94   23  Hyderabad     58    Yes

In [18]:
#4. You can use @ to reference Python variables
age_limit = 22
df.query("Age > @age_limit")

    ID       Name  Age       City  Score Passed
3    4   Student4   23  Hyderabad     58    Yes
8    9   Student9   23  Bangalore     93    Yes
13  14  Student14   23      Delhi     58    Yes
18  19  Student19   23     Mumbai     93    Yes
23  24  Student24   23       Pune     58    Yes
28  29  Student29   23    Chennai     93    Yes
33  34  Student34   23  Hyderabad     58    Yes
38  39  Student39   23  Bangalore     93    Yes
43  44  Student44   23      Delhi     58    Yes
48  49  Student49   23     Mumbai     93    Yes
53  54  Student54   23       Pune     58    Yes
58  59  Student59   23    Chennai     93    Yes
63  64  Student64   23  Hyderabad     58    Yes
68  69  Student69   23  Bangalore     93    Yes
73  74  Student74   23      Delhi     58    Yes
78  79  Student79   23     Mumbai     93    Yes
83  84  Student84   23       Pune     58    Yes
88  89  Student89   23    Chennai     93    Yes
93  94  Student94   23  Hyderabad     58    Yes
98  99  Student99   23  Bangalore     93    Yes

In [20]:
#5. Logical operators (and,or,not)
df.query("Age ==19 and City == 'Delhi'")

    ID       Name  Age   City  Score Passed
19  20  Student20   19  Delhi     30     No
49  50  Student50   19  Delhi     30     No
79  80  Student80   19  Delhi     30     No

In [21]:
#6. Chained comparisons
df.query("19 < Age <= 22")

    ID       Name  Age       City  Score Passed
0    1   Student1   20     Mumbai     37     No
1    2   Student2   21      Delhi     44     No
2    3   Student3   22  Bangalore     51    Yes
5    6   Student6   20       Pune     72    Yes
6    7   Student7   21     Mumbai     79    Yes
7    8   Student8   22      Delhi     86    Yes
10  11  Student11   20    Chennai     37     No
11  12  Student12   21       Pune     44     No
12  13  Student13   22     Mumbai     51    Yes
15  16  Student16   20  Hyderabad     72    Yes
16  17  Student17   21    Chennai     79    Yes
17  18  Student18   22       Pune     86    Yes
20  21  Student21   20  Bangalore     37     No
21  22  Student22   21  Hyderabad     44     No
22  23  Student23   22    Chennai     51    Yes
25  26  Student26   20      Delhi     72    Yes
26  27  Student27   21  Bangalore     79    Yes
27  28  Student28   22  Hyderabad     86    Yes
30  31  Student31   20     Mumbai     37     No
31  32  Student32   21      Delhi     44     No
32  33  Student33   22  Bangalore     51    Yes
35  36  Student36   20       Pune     72    Yes
36  37  Student37   21     Mumbai     79    Yes
37  38  Student38   22      Delhi     86    Yes
40  41  Student41   20    Chennai     37     No
41  42  Student42   21       Pune     44     No
42  43  Student43   22     Mumbai     51    Yes
45  46  Student46   20  Hyderabad     72    Yes
46  47  Student47   21    Chennai     79    Yes
47  48  Student48   22       Pune     86    Yes
50  51  Student51   20  Bangalore     37     No
51  52  Student52   21  Hyderabad     44     No
52  53  Student53   22    Chennai     51    Yes
55  56  Student56   20      Delhi     72    Yes
56  57  Student57   21  Bangalore     79    Yes
57  58  Student58   22  Hyderabad     86    Yes
60  61  Student61   20     Mumbai     37     No
61  62  Student62   21      Delhi     44     No
62  63  Student63   22  Bangalore     51    Yes
65  66  Student66   20       Pune     72    Yes
66  67  Student67   21     Mumbai     79    Yes
67  68  Student68   22      Delhi     86    Yes
70  71  Student71   20    Chennai     37     No
71  72  Student72   21       Pune     44     No
72  73  Student73   22     Mumbai     51    Yes
75  76  Student76   20  Hyderabad     72    Yes
76  77  Student77   21    Chennai     79    Yes
77  78  Student78   22       Pune     86    Yes
80  81  Student81   20  Bangalore     37     No
81  82  Student82   21  Hyderabad     44     No
82  83  Student83   22    Chennai     51    Yes
85  86  Student86   20      Delhi     72    Yes
86  87  Student87   21  Bangalore     79    Yes
87  88  Student88   22  Hyderabad     86    Yes
90  91  Student91   20     Mumbai     37     No
91  92  Student92   21      Delhi     44     No
92  93  Student93   22  Bangalore     51    Yes
95  96  Student96   20       Pune     72    Yes
96  97  Student97   21     Mumbai     79    Yes
97  98  Student98   22      Delhi     86    Yes

In [22]:
#7. .query() returns a copy, not a view

filtered = df.query("Age < 21")
filtered

     ID        Name  Age       City  Score Passed
0     1    Student1   20     Mumbai     37     No
4     5    Student5   19    Chennai     65    Yes
5     6    Student6   20       Pune     72    Yes
9    10   Student10   19  Hyderabad     30     No
10   11   Student11   20    Chennai     37     No
14   15   Student15   19  Bangalore     65    Yes
15   16   Student16   20  Hyderabad     72    Yes
19   20   Student20   19      Delhi     30     No
20   21   Student21   20  Bangalore     37     No
24   25   Student25   19     Mumbai     65    Yes
25   26   Student26   20      Delhi     72    Yes
29   30   Student30   19       Pune     30     No
30   31   Student31   20     Mumbai     37     No
34   35   Student35   19    Chennai     65    Yes
35   36   Student36   20       Pune     72    Yes
39   40   Student40   19  Hyderabad     30     No
40   41   Student41   20    Chennai     37     No
44   45   Student45   19  Bangalore     65    Yes
45   46   Student46   20  Hyderabad     72    Yes
49   50   Student50   19      Delhi     30     No
50   51   Student51   20  Bangalore     37     No
54   55   Student55   19     Mumbai     65    Yes
55   56   Student56   20      Delhi     72    Yes
59   60   Student60   19       Pune     30     No
60   61   Student61   20     Mumbai     37     No
64   65   Student65   19    Chennai     65    Yes
65   66   Student66   20       Pune     72    Yes
69   70   Student70   19  Hyderabad     30     No
70   71   Student71   20    Chennai     37     No
74   75   Student75   19  Bangalore     65    Yes
75   76   Student76   20  Hyderabad     72    Yes
79   80   Student80   19      Delhi     30     No
80   81   Student81   20  Bangalore     37     No
84   85   Student85   19     Mumbai     65    Yes
85   86   Student86   20      Delhi     72    Yes
89   90   Student90   19       Pune     30     No
90   91   Student91   20     Mumbai     37     No
94   95   Student95   19    Chennai     65    Yes
95   96   Student96   20       Pune     72    Yes
99  100  Student100   19  Hyderabad     30     No