In [1]:
import pandas as pd
df = pd.read_csv("data.csv")

In [2]:
df

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [4]:
pd.read_csv("data.csv", usecols=["Name", "Age"], nrows=5)

     Name  Age
0  Aniket   21
1     Ram   22
2    Siya   21
3     Raj   16
4  Prachi   22

In [5]:
df.to_csv("output.csv", index=False)

In [6]:
df

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [7]:
#Excel files
df = pd.read_excel("data.xlsx")

In [8]:
df

         Name    School  Age  Marks
0      Aniket      CSPM   21     78
1         Ram   Bhalero   22     67
2        Siya      MEMS   21     56
3         Raj  Montfort   16     78
4      Prachi       KVY   22     89
5      Soumya       BPS   14     90
6      Yashmi       BPS   17     99
7     Nikitha       CSM   18     98
8   Shrinidhi       BPS   15     87
9      Tanaya       CSM   14     85
10     Taniya       BPS   12     95

In [15]:
pd.read_excel("Book1.xlsx",sheet_name="Sheet1")

     name  age school
0   umesh   20    kyc
1  ramesh   21    mbs
2  suresh   22    bps
3    tung   23   cbse
4    wohh   18    ssc
5   rainy   14    rbi
6   sunny   12   gnps
7    rome   23    bit
8    doma   12    cps

In [16]:
df.to_excel("output.xlsx",index=False)